name: $(date:yyyyMMdd)-$(BuildID)
trigger:
 - master
 - dunfell

schedules:
- cron: "0 8 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

stages:
- stage: eve
  displayName: Eve
  dependsOn: []
  jobs:
  - job: eve
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - template: templates/steps_setup.yml
      parameters:
        machine: 'eve'
        build_branch: $(Build.SourceBranchName)
    - template: templates/steps_build.yml

- stage: x86
  displayName: X86
  dependsOn: []
  jobs:
  - job: x86
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - template: templates/steps_setup.yml
      parameters:
        machine: 'x86'
        build_branch: $(Build.SourceBranchName)
    - template: templates/steps_build.yml

- stage: mediatek8173
  displayName: MEDIATEK8173
  dependsOn: []
  jobs:
  - job: mediatek8173
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - template: templates/steps_setup.yml
      parameters:
        machine: 'mediatek8173'
        build_branch: $(Build.SourceBranchName)
    - template: templates/steps_build.yml
